version: '3.8'

# Thay thế <username> bằng tên Docker Hub của bạn
# Ví dụ: myusername/prm-backend
# Ví dụ: myusername/prm-frontend

networks:
  app-network:
    driver: bridge

volumes:
  # Volume để lưu trữ dữ liệu database nếu có (chưa có mongo service, nhưng nên có)
  # Volume để lưu trữ logs của Nginx (optional)
  nginx-logs:

services:
  # =========================================================
  # 1. DỊCH VỤ BACKEND
  # =========================================================
  backend:
    # Lấy ảnh từ Docker Hub. Bỏ phần 'build' khỏi file này.
    image: giason/prm-backend:latest
    container_name: prm-backend
    restart: unless-stopped
    # Dùng expose thay vì ports để chỉ mở cổng nội bộ cho Nginx
    expose:
      - "5000"
    environment:
      # Thay đổi NODE_ENV sang production
      - NODE_ENV=production
      - PORT=5000
    env_file:
      # Đảm bảo file .env chứa các biến Production
      - .env
    networks:
      - app-network
    # Giữ lại Healthcheck nếu cần thiết

  # =========================================================
  # 2. DỊCH VỤ FRONTEND
  # =========================================================
  frontend:
    # Lấy ảnh từ Docker Hub. Bỏ phần 'build' khỏi file này.
    image: giason/prm-frontend:latest
    container_name: prm-frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # SỬA BIẾN MÔI TRƯỜNG CHO FRONTEND
      # Đảm bảo frontend gọi API qua Nginx Reverse Proxy (domain)
      - VITE_API_URL=http://mt1607.xyz/prm
    env_file:
      - .env
    networks:
      - app-network
    # Tạm bỏ depends_on nếu không có database, nhưng nên đảm bảo Backend chạy trước
    depends_on:
      - backend

  # =========================================================
  # 3. DỊCH VỤ NGINX (REVERSE PROXY)
  # =========================================================
  nginx:
    image: nginx:alpine
    container_name: prm-nginx
    restart: unless-stopped
    # Mở cổng 80 của VPS (Public) tới cổng 80 của Nginx Container
    ports:
      - "80:80"
    volumes:
      # Map file cấu hình Nginx mới
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - frontend
      - backend