version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  nginx-logs:

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: prm-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5000
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  frontend:
    build:
      context: ./front-end/fe-project-manager
      dockerfile: Dockerfile
    container_name: prm-frontend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "80"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy
  
  nginx:
    image: nginx:alpine
    container_name: prm-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
